name: Cypress Tests

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 * * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        build: npm run build
        start: npm start

    # Save videos and screenshots as test artifac
    - name: Archive test results
      uses: actions/upload-artifact@v2
      with:
        name: test-result-report
        path: /home/runner/work/dimagi-qa/dimagi-qa/report.html
        retention-days: 2
    - name: Cypress test results
      uses: actions/upload-artifact@v2
      with:
        name: cypress-report
        path: /home/runner/work/dimagi-qa/dimagi-qa/report.html
        retention-days: 2
