name: Cypress Tests

on:
  push:
    branches: [ formplayer_cypress ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./CypressTests
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        build: npm run build
        start: npm start
        
    - name: Cypress test results
      uses: actions/upload-artifact@v2
      with:
        name: cypress-report
        path: /home/runner/work/dimagi-qa/dimagi-qa/report.html
        retention-days: 2
