name: Cypress Tests

on:
  push:
    branches: [ formplayer_cypress ]
    
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: CyPressTest
          build: npm run build
          start: npm start
          record: truE
        env:
          CYPRESS_RECORD_KE: ${{secrets.CYPRESS_RECORD_KEY}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}