name: Cypress Tests

on:
  push:
    branches: [ formplayer_cypress ]
    
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: CyPressTest
         # run : npm run cypress:run
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
          CYPRESS_QA_URL: ${{ secrets.DIMAGIQA_URL }}
          CYPRESS_LOGIN_USERNAME: ${{ secrets.DIMAGIQA_LOGIN_USERNAME }}
          CYPRESS_LOGIN_PASSWORD: ${{ secrets.DIMAGIQA_LOGIN_PASSWORD }}
         # GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}