# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: NY App Tests

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r USH_Apps/NY_CICT/requirements.txt
        sudo apt-get install xvfb

    # - name: Execute tests
    #   uses: joonvena/robotframework-docker-action@v0.1
    #   env:
    #     BROWSER: chrome
    #     ROBOT_TESTS_DIR: ${{ github.workspace }}/robot_tests
    #     ROBOT_REPORTS_DIR: ${{ github.workspace }}/reports
        
    - name: NY App Tests
      env:
        DIMAGIQA_MAIL_USERNAME: ${{ secrets.DIMAGIQA_MAIL_USERNAME }}
        DIMAGIQA_MAIL_PASSWORD: ${{ secrets.DIMAGIQA_MAIL_PASSWORD }}
        DIMAGIQA_RF_SECRETS:  ${{ secrets.DIMAGIQA_RF_SECRETS }}
        DIMAGIQA_RF_PASSWORD:  ${{ secrets.DIMAGIQA_RF_PASSWORD }}
      run: |
        echo "NOW=$(date +'%m-%d %H:%M')" >> $GITHUB_ENV
        echo ${{env.NOW}}
        robot -d robot -d ./USH_Apps/NY_CICT/Reports './USH_Apps/NY_CICT/Tests'

    - name: Zip Reports folder
      uses: papeloto/action-zip@v1
      if: always()
      with:
          files: ./USH_Apps/NY_CICT/Reports/
          dest: ./USH_Apps/NY_CICT/Reports.zip

    - name: Send Failure Email on Deploy Event
      uses: dawidd6/action-send-mail@v3
      if: always()
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.DIMAGIQA_MAIL_USERNAME}}
        password: ${{secrets.DIMAGIQA_MAIL_PASSWORD}}
        subject: NY App Tests in ny-staging-cdms domain[#${{github.run_number}}], ${{env.NOW}}
        to: kbordoloi@dimagi.com, ktripathy@dimagi.com
        from: <${{secrets.DIMAGIQA_MAIL_USERNAME}}>
        html_body: Please find attached the run report.
        attachments:  /home/runner/work/dimagi-qa/dimagi-qa/USH_Apps/NY_CICT/Reports.zip
        priority: normal

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-result-reports
        path: /home/runner/work/dimagi-qa/dimagi-qa/USH_Apps/NY_CICT/Reports.zip
        retention-days: 2
